### ISSUE TITLE
Daha detaylı bir readme

### ISSUE THREAD

**Issue by muhammetaydinn** [enescaakir/MHRS-OtomatikRandevu#2]
Merhabalar, elinize sağlık proje için. Readme üzerinde kurulum ve çalıştırma için de bir şeyler ekleyebilir misiniz?
Sıfırdan kurulum şeklinde. Bağımlılıkları vs.

**Comment by enescaakir** [comment]
Merhaba, uygulama klonlanıp çalıştırılabilir durumdadır. Kurulum ihtiyacı bulunmamaktadır.
