### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401

### ISSUE THREAD

**Issue by muhammetaydinn** [enescaakir/MHRS-OtomatikRandevu#4]
Greetings, I got this error after a few tries, I think it was due to excessive requests, but I can't be sure.
What do you think causes this error?
Console Output:
```
MHRS Otomatik Randevu Sistemine Hoşgeldiniz.
Lütfen giriş yapmak için bilgilerinizi giriniz.
TC: ***********
Şifre:  ***********
Giriş Yapılıyor...
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401.
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient client, Task`1 responseTask, Boolean usingResponseHeadersRead, CancellationTokenSource linkedCTS, Func`4 deserializeMethod, TJsonOptions jsonOptions, CancellationToken cancellationToken)
```

**Comment by enescaakir** [comment]
Hi Muhammet, can you check the token.txt file is it filled with JWT token?

**Comment by muhammetaydinn** [comment]
Yes, I think the reason is that the 'token.txt' file is created or created in another folder.
``` var rawPath = Directory.GetCurrentDirectory()
                 .Replace("\\", "/")
                 .Split('/')
                 .SkipLast(3)
                 .ToList();
```
  
In this code, when `SkipLast(3)` was done, the 'token.txt' location was `C:\Users\token.txt` and I was getting this error.
`Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\token.txt' is denied.`
Instead I did `SkipLast(1)` and
`C:\Users\usr\MHRS-AutoAppointment\token.txt`
created the `token.txt` file in the folder.
So this is how I solved it.

**Comment by muhammetaydinn** [comment]
By the way, I'm not sure if this is the right solution, but token.txt should be located in our project folder.

**Comment by enescaakir** [comment]
Seems like cause is _token.txt_ location. But it is working in my local, maybe we can find a generic solution with pair work.

**Comment by alidgn** [comment]
If you want to locate the "token.txt" file outside of the project root (for example in the "Desktop" folder) you can use `Environment.GetFolderPath(Environment.SpecialFolder.Desktop)`. This operation gives you desktop folder of the current user.

**Comment by alidgn** [comment]
> No we don't want to locate file outside of the projet. Here is the problem: We use same code but for me file has been created outside of the project, for him inside.

Then you can use `Environment.CurrentDirectory` operation to get execution directory.

Example code:
`Path.Combine(Environment.CurrentDirectory, "token.txt");`

**Comment by muhammetaydinn** [comment]
Yeah this will fix my problem and it's generic solution. Thanks.
