### ISSUE TITLE
New feature suggestion: set appointment date

### ISSUE THREAD

**Issue by muhammetaydinn** [enescaakir/MHRS-OtomatikRandevu#6]
Set or display appointments within a certain period of time in the appointment search section.
For example, if I can only go this week, I should only make an appointment next week among the dates offered by that MHRS.
We can also choose specific dates and hours by writing this more generically in the future.
I'm busy these days, but I'll be here to add when I'm free.

**Comment by enescaakir** [comment]
Great idea, when you start coding i can support you.

**Comment by enescaakir** [comment]
feature added.
