### ISSUE TITLE
Bug on Selecting Sub-Location for Istanbul.

### ISSUE THREAD

**Issue by alidgn** [enescaakir/MHRS-OtomatikRandevu#7]
When we choose a sub-region for Istanbul, the license plate and the selection information are combined and converted into an integer. However, since the condition in the while checks between 1 and 81, the flow cannot be exited. For example, when Istanbul is selected as Europe, "34"+"1" = "341" falls outside the range in the while condition.

**Comment by enescaakir** [comment]
Thanks Ali, it fixed now.
